---
title: "Micrometeorology Analysis in Colorado"
author: "Kaydee S. Barker"
date: '2022-04-27'
output: 
  html_document:
    
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, warning=FALSE}

rm(list=ls()) #clear global environment/workspace

library(rvest)
library(tidyverse)
library(lubridate)
library(dplyr) #lots of functions
library(tidyr)
library(ggplot2) #all of the graphs
library(ggthemes) #themes colors for plots
library(zoo) #interpolate data
library(lme4)
library(lmerTest)
library(emmeans) #stats summarize???
library(tidyquant) #moving averages

knitr::opts_chunk$set(echo = TRUE) #global setting to show code

customPalette <- c("#E69F00", "#56B4E9", "#009E73", "#CC79A7")

```

```{r data read, warning=FALSE}

COweather <- read_csv("COstations_weather.csv")

#View(COweather)

COdata <- COweather %>%
  mutate(Date = mdy(Date)) %>%
  mutate_at(vars(Date), funs(year, month)) %>%
  mutate(DOY = format(Date, "%j")) %>%
  filter(DOY >= 131 & DOY <= 284) %>% #filter to May 10 - Oct 10 
  mutate(Avg_T = na.approx(Avg_T), Max_T = na.approx(Max_T), Min_T = na.approx(Min_T), 
         RH_max = na.approx(RH_max), RH_min = na.approx(RH_min), VP = na.approx(VP), 
         Precip = na.approx(Precip), Wind = na.approx(Wind), Srad = na.approx(Srad), 
         Rso = na.approx(Rso), ASCE_ETr = na.approx(ASCE_ETr), ASCE_ETo = na.approx(ASCE_ETo), 
         ASCE_hr_ET = na.approx(ASCE_hr_ET), PK_ET = na.approx(PK_ET)) #interpolate missing values via linear interpolation (na.spline = polynomial)

#View(COdata)

#write.csv(COdata, "~/Dropbox/Kaydee's docs/Code/Micrometeorology-CO-irrigatedsites/COdata.csv", row.names=FALSE)

COdata2 <- read_csv("COdata2.csv") %>%
  mutate_at(vars(ETr, ETo, Kc, ETc), as.numeric)

# Means/summarize dataset across years
COdata_means <- COdata2 %>% 
  group_by(Station, year, month, DOY) %>%
  summarise_all(funs(mean(., na.rm=TRUE)))

# Sums/summarize dataset monthly
COdata_monthly <- COdata2 %>% 
  group_by(Station, month) %>%
  summarise_at(vars(-Station_ID,-Lat, -Long, -Elev_ft, -Elev_m, -Date), mean)

#write.csv(COdata_monthly, "~/Dropbox/Kaydee's docs/Code/Micrometeorology-CO-irrigatedsites/COdata_monthly.csv", row.names=FALSE)

# Sums/summarize dataset yearly
COdata_yearly <- COdata2 %>% 
  group_by(Station, year) %>%
  summarise_at(vars(-Station_ID,-Lat, -Long, -Elev_ft, -Elev_m, -Date, -DOY), sum)

#write.csv(COdata_yearly, "~/Dropbox/Kaydee's docs/Code/Micrometeorology-CO-irrigatedsites/COdata_yearly.csv", row.names=FALSE)

yearly <- read_csv("yearly2.csv")

```

```{r, warning=FALSE}
# Individual sites datasets

#Greeley
Gly <- COdata2 %>% 
  filter(Station_ID == "gly04")

#Rocky Ford
RF <- COdata2 %>%
  filter(Station_ID == "rfd01")

#Rogers Mesa Research Station
RM <- COdata2 %>%
  filter(Station_ID != "gly04") %>%
  filter(Station_ID != "rfd01") %>%
  filter(Station_ID != "ctr01")

#Center
Ctr <- COdata2 %>%
  filter(Station_ID == "ctr01")

```

# Analysis

## Temperatures
### Average Growing Season Air Temperature Per Site
```{r, warning=FALSE}

ggplot(COdata, aes(x = DOY, y = Avg_T, color = Station)) +
  geom_point(shape=21, size=2) + geom_line() +
  theme_few() + theme(legend.position="right") +
  labs(x = "Day of Year", y = "Average Temperature (C)") + 
  scale_color_manual(values=customPalette)

ggplot(COdata_monthly, aes(x = month, y = Avg_T, color = Station)) +
  geom_point(shape=21, size=2) + geom_line() +
  theme_few() + theme(legend.position="right") +
  labs(x = "Day of Year", y = "Average Temperature (C)") +
  scale_color_manual(values=customPalette)


```

## Precipitation
### Growing Season Precipitation Per Site Per Year
```{r, warning=FALSE}

COdata %>%
  mutate_at(vars(month), funs(factor)) %>%
ggplot(., aes(x=month, y=Precip, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_x_discrete(labels=c("5"="May", "6"="June", "7"="Jul.", "8"="Aug.", "9"="Sept.", "10"="Oct.")) +
  xlab("Month") +  ylab("Precipitation in mm") +
  theme_few() + scale_color_manual(values=customPalette)

COdata %>%
  mutate_at(vars(year), funs(factor)) %>%
ggplot(., aes(x=year, y=Precip, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  xlab("Year") +  ylab("Precipitation in mm") +
  theme_few() + scale_color_manual(values=customPalette)


```

## Evapotranspiration
```{r, warning=FALSE}

#Create function to calculate ET - Need latitude and longitude, DOY, Elevation, Tmax, Tmin

#CO_ET <- COdata2 %>%
#  mutate(ET_func = penman(Tmin = Min_T, Tmax = Max_T, U2 = NA, Ra = NA, lat = Lat, Rs = NA, tsun = NA,
#	CC = NA, ed = NA, Tdew = NA, RH = ((RH_max + RH_min)/2), P = NA, P0 = NA,
#	z = Elev_m, crop='short', na.rm = FALSE))

ggplot(COdata2, aes(x=Station, y=ETc, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  xlab("Site") +  ylab("Evapotranspiration (mm/day)") +
  theme_few() + scale_color_manual(values=customPalette)

ggplot(COdata2, aes(x=year, y=ETc, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  xlab("Year") +  ylab("Evapotranspiration (mm/day)") +
  theme_few() + scale_color_manual(values=customPalette)

COdata2 %>%
  filter(Station == "Center") %>%
ggplot(., aes(x = DOY, y = ETc)) +
  geom_point(shape=21, size=2) + geom_ma(ma_fun = SMA, n = 15) +
  theme_few() + theme(legend.position="right") +
  labs(x = "Day of Year", y = "Evapotranspiration (mm/day)") +
  scale_color_manual("#009E73")

COdata2 %>%
  filter(Station == "Greeley") %>%
ggplot(., aes(x = DOY, y = ETc)) +
  geom_point(shape=21, size=2) + geom_ma(ma_fun = SMA, n = 15) +
  theme_few() + theme(legend.position="right") +
  labs(x = "Day of Year", y = "Evapotranspiration (mm/day)") +
  scale_color_manual("#009E73")

COdata2 %>%
  filter(Station == "Rogers Mesa") %>%
ggplot(., aes(x = DOY, y = ETc)) +
  geom_point(shape=21, size=2) + geom_ma(ma_fun = SMA, n = 15) +
  theme_few() + theme(legend.position="right") +
  labs(x = "Day of Year", y = "Evapotranspiration (mm/day)") +
  scale_color_manual("#009E73")

COdata2 %>%
  filter(Station == "Rocky Ford") %>%
ggplot(., aes(x = DOY, y = ETc)) +
  geom_point(shape=21, size=2) + geom_ma(ma_fun = SMA, n = 15) +
  theme_few() + theme(legend.position="right") +
  labs(x = "Day of Year", y = "Evapotranspiration (mm/day)") +
  scale_color_manual("#009E73")


```

## Irrigation
```{r}

ggplot(yearly, aes(x=year, y=IRR, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  xlab("Year") +  ylab("Irrigation Requirement (mm)") +
  theme_few() + scale_color_manual(values=customPalette)

ggplot(yearly, aes(x=year, y=IRRADJ, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  xlab("Year") +  ylab("Adjusted Irrigation Requirement (mm)") +
  theme_few() + scale_color_manual(values=customPalette)

ggplot(yearly, aes(x=Station, y=IRRADJ, fill=Station)) + 
  geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  xlab("Site") +  ylab("Adjusted Irrigation Requirement (mm)") +
  theme_few() + scale_color_manual(values=customPalette)

```

```{r}

```

